version: 2

defaults: &defaults
  working_directory: ~/qlik-heatmap-chart
  docker:
    - image: circleci/node:stretch
  environment:
    GITHUB_ORG: "qlik-oss"
    GITHUB_REPO: "QlikSense_Extension_2DimHeatmap"
    PACKAGE_NAME: "qlik-heatmap-chart"

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build and package
          command: npm run build
          environment:
            NODE_ENV: production
      - persist_to_workspace:
          root: ~/qlik-heatmap-chart
          paths:
            - build
      - store_artifacts:
          path: build/qlik-heatmap-chart.zip
          destination: qlik-heatmap-chart.zip
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qlik-heatmap-chart
      - run:
          name: Install ghr
          command: scripts/install-ghr.sh
      - run:
          name: Create GitHub Release
          command: scripts/create-release.sh $GITHUB_ORG $GITHUB_REPO $PACKAGE_NAME

workflows:
  version: 2
  master_flow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
